### ISSUE TITLE
"Firebird 1.3" Clicking on the direction "touchpad" too many times causes firebird to crash

### ISSUE THREAD

**Issue by lexterror** [nspire-emus/firebird#76]
Android Version: 6.0.1 (Marshmallow)
Firebird Version: 1.2 (Android)

The flash OS randomly freezes and restarts afterwards.
Firebird does not freeze nor does Android...

**Comment by Vogtinator** [comment]
What do you mean by "flash OS"?

**Comment by lexterror** [comment]
The Nspire OS running on Firebird

**Comment by lexterror** [comment]
I tried Nspire v3 and v4 and it's the same problem (only on android). The Windows version works fine

**Comment by lexterror** [comment]
It freezes more often if I go to "settings" and then return to the "keypad". But even if I don't go to "Settings" it still happens...

**Comment by lexterror** [comment]
it's always random

**Comment by Vogtinator** [comment]
Please don't double post, you can edit comments!

What exactly happens, does the OS not react to keyboard events for 30 seconds and then reboots?

**Comment by lexterror** [comment]
OS does not respond for 5 seconds then reboots

**Comment by Vogtinator** [comment]
Ok, that sounds like it triggers the watchdog somehow. Do you use Ndless in your image? How did you create the flash image?

Do you have access to the ADB log?

**Comment by lexterror** [comment]
I did not use Ndless. I'm away from school right now and I just used firebird to create the flash...

**Comment by lexterror** [comment]
I tried the latest version "Firebird Emulator 1.3" and I have the same issue on two different devices:
-Samsung J3 ATT Phone
-Samsung Tab A7

**Comment by Vogtinator** [comment]
Can you try your boot1/flash combo with desktop firebird?

**Comment by lexterror** [comment]
It works fine on Windows... It's only Android that's not working. Is that what you mean?

**Comment by Vogtinator** [comment]
If you enable ```Enter debugger on warning``` in the debugging options, does the system still crash or show ```In Debugger``` instead?

**Comment by lexterror** [comment]
After the system freezes it shows "in debugger" and does not reboot. In the previous version 1.2 it used to reboot after freezing. Hope that helps.

**Comment by Vogtinator** [comment]
Ok, that means the OS crashed, probably due to a bug in the JIT or other core parts.

Unfortunately debugging that isn't easy without having easy access to a system with easy reproducability :-/

**Comment by lexterror** [comment]
Thanks for your help. I will keep trying the latest versions for android.

**Comment by lexterror** [comment]
I just noticed something: right before the debugger screen shows up the "speed" slows down to between 24% and 25% and crashes at 25%.

**Comment by gutsystudio** [comment]
Some fix please? Every body in my school have the same probleme, trying using the touch Pad trig it, with the android Nougat and te 4.4 also
Please we love this emu and we use it somuch in our comunity. Fix it please. Thanks.

**Comment by Vogtinator** [comment]
So far I haven't found a way to reproduce the issue reliably, although I did see it happen once or twice on older builds.

**Comment by Vogtinator** [comment]
I found a way to reproduce it semi-reliably: By repeatedly opening and closing the newlib-c++ ndless sdk example I can get firebird to abort due to unexpected OS behaviour. Unfortunately that kind of issue is not that easy to debug, but as it only happens with the ARM JIT I should be able to find the issue by disabling certain features and comparing the result.

**Comment by gutsystudio** [comment]
Thanks my friend for your answer and your  and your willingness to improve that great emulator. It is people like you who inspire young people like us to follow their example and reach our goals no matter what it costs. Thanks.

**Comment by Vogtinator** [comment]
I found the issue I stumbled upon and fixed it. Hopefully it fixed the crashes you're getting as well.
Here's a recent build without .text relocations:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1061956/firebird.apk.zip)

**Comment by lexterror** [comment]
It still freezes at 20% (it freezes more often if you press buttons faster...)

**Comment by Vogtinator** [comment]
20% of what?

**Comment by lexterror** [comment]
speed

**Comment by Vogtinator** [comment]
That is normal, the speed indication does not matter at all.

What do you do to get it to crash?

**Comment by lexterror** [comment]
(1) I use firebird for a few minutes pressing buttons normally, then I go back a few minutes later and it crashes
(2) I start firebird and I press the different buttons at a fast speed and it crashes

**Comment by gutsystudio** [comment]
I'm going to try it in my Moto Z Play with stock rooted Nougat 7.0.1.
Thanks my friend for your work and answer.

**Comment by gutsystudio** [comment]
The error of the beginning has already disappeared. It works fine while I do not use the touchpad to move the arrow around more than twice followed or to press it several times in any direction. If I do either of those two things, it freezes and restarts after about 20 seconds if the option '' Enter debugger on warnings '' is disabled, and if not, it stays in debugger indefinitely.
I use the same files (Boot1 + Flash + Snapshot) with Firebird v1.3 for Windows and everything works wonderfully in the mobil and normal version.
Thank you for your kind advice.

**Comment by lexterror** [comment]
yes, it appears it's the direction buttons that are not working if pressed many times. I should have been more specific earlier. But it's definitely still crashing if I move the arrows too many times.

**Comment by lexterror** [comment]
Is the issue going to be fixed?

**Comment by Vogtinator** [comment]
That this issue got closed was an unintentional side effect of merging the aarch64jit branch, I reopened it.

I cannot reproduce the issue you have, but I'll upload another apk for you to test soon.

**Comment by gutsystudio** [comment]
Thanks and somuch. We will be in touch and waiting impatiently for trying your next apk.
Have a good day my friend.

**Comment by Vogtinator** [comment]
This APK contains some more rigorous cache flushing:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1065056/firebird.apk.zip)

**Comment by lexterror** [comment]
firebird crashed at 24% while loading the OS 

it doesn't start now... I think that what you just modified has to do with my issue.

**Comment by Vogtinator** [comment]
> I just noticed that you can click virtually anywhere on the touchpad. Would it be possible to "limit" the touchpad to only "5" buttons? (Up/Down/Left/Right/Center) maybe it's a "sensor" problem?

No, the touchpad allows free cursor movement, just like on hardware.

**Comment by lexterror** [comment]
I think the "free cursor movement" might be the problem because when I press too many times in different directions that's when it crashes.

the apk you just posted is still not loading... the speed is down to less than 20% (the regular apk loads in 1 minute or less)

**Comment by Vogtinator** [comment]
> I think the "free cursor movement" might be the problem because when I press too many times in different directions that's when it crashes.

Works fine here as well, I haven't gotten to crash the OS in firebird since I fixed two unrelated bugs that are likely only triggered by ndless apps anyway.

> the apk you just posted is still not loading... the speed is down to less than 20% (the regular apk loads in 1 minute or less)

Yes, that's unfortunately what rigorous cache flushing means, every single instruction now causes a total cache eviction. However, if the issue is gone we at least now what it's likely caused by.

**Comment by lexterror** [comment]
Ok, I'm still waiting... I will update

**Comment by gutsystudio** [comment]
Thank you my friend for assisting us. 
Testing the new apk on a Moto Z Play with Nougat, at starting the emu is frozen on the OS loading screen for almost two hours ago.
Something is still wrong i think, but I am absolutely sure that you can fix it and the android Firebird that we're testing now will be as perfect as its equivalent in the windows operating system.
Thank you somuch.

**Comment by gutsystudio** [comment]
Some news about a real fixed apk, please?

**Comment by Vogtinator** [comment]
As I cannot reproduce the issue you have and the attempt to confirm an issue with cache flushing turned out to be too slow, I have no idea how to proceed here.

I got similiar issues on a samsung galaxy s3 mini, but those were caused by lack of available RAM.

**Comment by lexterror** [comment]
Thanks for your help!

**Comment by gutsystudio** [comment]
Please Vogtinator , what cel do you have, and with what android rom version, rooted o not, stock o custom do you use to run emu Firebird whitout any issues? 
We need your help to be happy whit this great emu of all time my friend.

**Comment by Vogtinator** [comment]
One desperate attempt: This disables indirect jumps inside JIT code.

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1066704/firebird.apk.zip)

**Comment by lexterror** [comment]
It's freezes again when I press on the direction touch pad too many times.

Vogtinator: It would be of great help if you could let us know what type of phone you're using. Maybe I can buy something similar or figure out what the problem might be. Thanks!

**Comment by Vogtinator** [comment]
That video is indeed helpful, it shows that it's not a hard OS crash, but just that the watchdog triggers for some reason.

It might be possible to work around that by not handling touchpad events while the IRQ hasn't been acked yet. I need to find a way to reproduce it first, though.

**Comment by Vogtinator** [comment]
Good news, I was just able to reproduce the issue here! It took over a minute of hitting the same key over and over again, but with the same result.

**Comment by gutsystudio** [comment]
You just granted me an excellent and better afternoon with that good news. 
Remember, that i trust that you will soon find a solution. 
Being a genius like you, would only be a matter of time to achieve it.

**Comment by Vogtinator** [comment]
I implemented a pretty ugly workaround (commit 6cd632d93f652e4e34725f0ad6e5de63a1ead6c5) and here's a binary for testing:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1069593/firebird.apk.zip)

If you can, please save the adb logs that you get while trying to reproduce the issue, whether it happens or not.

**Comment by gutsystudio** [comment]
Thanks my friend. I'll try it immediately.

**Comment by lexterror** [comment]
firebird restarts the OS right after it crashes, where is the location of the adb logs?

**Comment by gutsystudio** [comment]
I tried the new apk and the result is that when using the directional keys quickly to make the cursor visible it automatically restarts instead of being frozen the OS as before.
That means you are close to solving that annoying malfunction. Thanks my friend and cheer up.

**Comment by Vogtinator** [comment]
> firebird restarts the OS right after it crashes, where is the location of the adb logs?

https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat

> I tried the new apk and the result is that when using the directional keys quickly to make the cursor visible it automatically restarts instead of being frozen the OS as before.
That means you are close to solving that annoying malfunction

No, that's just a side effect of another change :-/

**Comment by lexterror** [comment]
Ok, I was able to get the logs:

https://gist.github.com/lexterror/c4076c2b1c4c34e3156bef616785b6ed

Thanks!

**Comment by Vogtinator** [comment]
The logs show:

> FB DBG  : Workaround triggered

So it looks like I'm on the right track here. I'll broaden the workaround a bit and try to find a better way to avoid this. Maybe the keypad IRQs should be sticky instead.

**Comment by gutsystudio** [comment]
Yes sir. We will be waiting.

**Comment by Vogtinator** [comment]
With this APK I can trigger the workaround without crashing the OS in the process:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1072795/firebird.apk.zip)

Please keep ADB logs ready if it still does not work properly.

**Comment by lexterror** [comment]
It's working perfectly. Thanks so much! I've been using it for 45 minutes and no issues.

**Comment by gutsystudio** [comment]
Thanks my friend. You did it.
I knew you were going to fix it. Because If you were so genius to create it, it was also more than obvious that you're could also improve it more and more to perfection.
Now only remains to implement the same fix in the official version.
Congratulations, you're the best Vogtinator. Thank you somuch and expect my donation soon.

**Comment by Vogtinator** [comment]
So the workaround is confirmed, but this still needs a proper fix in place. I believe this might be caused by the emulation not being thread-safe, so I added some locks in the critical regions and can't reproduce the issue anymore. Please try as well:

[firebird.apk.zip](https://github.com/nspire-emus/firebird/files/1080676/firebird.apk.zip)

**Comment by lexterror** [comment]
It also works. No issues.

**Comment by gutsystudio** [comment]
Improving more and more to this wonderful emulator. 
Everything works fine. Thank you Vogtinator.

**Comment by Vogtinator** [comment]
As the fix landed in master, this can now finally be closed, yay!
